language: objective-c  #1
osx_image: xcode7.2 #2
#xcode_workspace: ./Tykoon/Tykoon.xcworkspace #3
xcode_project: V2SwiftApplication/V2SwiftApplication.xcodeproj # path to your xcodeproj folder
xcode_scheme: V2SwiftApplication #4
xcode_sdk: iphonesimulator9.2 #5

#/Users/nitesh.meshram/Documents/v2Apps/POCV2/V2SwiftApplication/V2SwiftApplication.xcodeproj